id: b9b454e56b5e4724985382a8d6d9671d
initial_creation_type: ocr
source_metadata:
  volumes:
    a1fbfdbce8a14ef293136aae2ee188a4:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
